// Generated by level_editor.py
// Cave drawing functions

static void draw_cave_room0(void) {
    uint8_t i;
    uint8_t cave_int = (dyn_exploding || (game_state == STATE_LEVEL_COMPLETE && (level_msg_timer & 4))) ? INTENSITY_BRIGHT : INTENSITY_DIM;
    zero_beam();
    intensity_a(cave_int);
    set_scale(0x7F);
    moveto_d(45, -85);
    draw_line_d(-30, 0);
    draw_line_d(0, -15);
    draw_line_d(-35, 0);
    draw_line_d(0, 85);
    draw_line_d(-30, 0);
    draw_line_d(0, -110);
    draw_line_d(95, 0);
    draw_line_d(0, 40);
    zero_beam();
    intensity_a(cave_int);
    set_scale(0x7F);
    moveto_d(45, -35);
    draw_line_d(-30, 0);
    draw_line_d(0, 127);
    draw_line_d(0, 8);
    draw_line_d(-35, 0);
    draw_line_d(0, -85);
    draw_line_d(-30, 0);
    zero_beam();
    intensity_a(cave_int);
    set_scale(0x7F);
    moveto_d(45, -35);
    draw_line_d(0, 127);
    draw_line_d(0, 33);
    draw_line_d(-95, 0);
    draw_line_d(0, -110);
    zero_beam();
    intensity_a(cave_int);
    set_scale(0x7F);
    moveto_d(15, -125);
    draw_line_d(0, 25);
    zero_beam();
    intensity_a(cave_int);
    set_scale(0x7F);
    moveto_d(-20, -125);
    draw_line_d(0, 25);
    zero_beam();
    intensity_a(cave_int);
    set_scale(0x7F);
    moveto_d(15, 100);
    draw_line_d(0, 25);
    zero_beam();
    intensity_a(cave_int);
    set_scale(0x7F);
    moveto_d(-20, 100);
    draw_line_d(0, 25);
    for (i = 0; i < cur_wall_count; i++) {
        if (walls_destroyed & (1 << i)) continue;
        zero_beam();
        intensity_a(dyn_exploding ? INTENSITY_BRIGHT : INTENSITY_HI);
        set_scale(0x7F);
        moveto_d(wall_y(i) + wall_h(i), wall_x(i));
        draw_line_d(0, wall_w(i));
        draw_line_d(-wall_h(i) * 2, 0);
        draw_line_d(0, -wall_w(i));
        draw_line_d(wall_h(i) * 2, 0);
    }
}

static void draw_cave_room1(void) {
    uint8_t i;
    uint8_t cave_int = (dyn_exploding || (game_state == STATE_LEVEL_COMPLETE && (level_msg_timer & 4))) ? INTENSITY_BRIGHT : INTENSITY_DIM;
    zero_beam();
    intensity_a(cave_int);
    set_scale(0x7F);
    moveto_d(50, -15);
    draw_line_d(0, -110);
    draw_line_d(-100, 0);
    draw_line_d(0, 127);
    draw_line_d(0, 123);
    draw_line_d(100, 0);
    draw_line_d(0, -110);
    zero_beam();
    intensity_a(cave_int);
    set_scale(0x7F);
    moveto_d(50, -15);
    draw_line_d(-30, 0);
    draw_line_d(0, -110);
    zero_beam();
    intensity_a(cave_int);
    set_scale(0x7F);
    moveto_d(20, -85);
    draw_line_d(-35, 0);
    zero_beam();
    intensity_a(cave_int);
    set_scale(0x7F);
    moveto_d(-15, -125);
    draw_line_d(0, 127);
    draw_line_d(0, 123);
    zero_beam();
    intensity_a(cave_int);
    set_scale(0x7F);
    moveto_d(-15, 85);
    draw_line_d(35, 0);
    draw_line_d(0, 40);
    zero_beam();
    intensity_a(cave_int);
    set_scale(0x7F);
    moveto_d(20, 85);
    draw_line_d(0, -70);
    draw_line_d(30, 0);
    for (i = 0; i < cur_wall_count; i++) {
        if (walls_destroyed & (1 << i)) continue;
        zero_beam();
        intensity_a(dyn_exploding ? INTENSITY_BRIGHT : INTENSITY_HI);
        set_scale(0x7F);
        moveto_d(wall_y(i) + wall_h(i), wall_x(i));
        draw_line_d(0, wall_w(i));
        draw_line_d(-wall_h(i) * 2, 0);
        draw_line_d(0, -wall_w(i));
        draw_line_d(wall_h(i) * 2, 0);
    }
}

void draw_cave(void) {
    if (current_room == 0) {
        draw_cave_room0();
    } else if (current_room == 1) {
        draw_cave_room1();
    }
}
