/*
 * sprites.h — Sprite declarations for QL Mode 8
 * Generated by sprite_editor.py
 */

#ifndef SPRITES_H
#define SPRITES_H

#include "game.h"

typedef struct {
    uint8_t w;
    uint8_t h;
    const uint8_t *data;
} Sprite;

extern const Sprite spr_player_fly_0;
extern const Sprite spr_player_walk_0;
extern const Sprite spr_player_walk_1;
extern const Sprite spr_bat_0;
extern const Sprite spr_bat_1;
extern const Sprite spr_spider_0;
extern const Sprite spr_snake_0;
extern const Sprite spr_miner_0;
extern const Sprite spr_dynamite_0;
extern const Sprite spr_explode_0;
extern const Sprite spr_wall_0;
extern const Sprite spr_lava_0;
extern const Sprite spr_cave_h_0;
extern const Sprite spr_cave_v_0;

#endif
