/*
 * sprites.h — Sprite declarations for QL Mode 8
 * Generated by sprite_editor.py
 */

#ifndef SPRITES_H
#define SPRITES_H

#include "game.h"

typedef struct {
    uint8_t w;
    uint8_t h;
    const uint8_t *data;
} Sprite;

extern const Sprite spr_player_fly;
extern const Sprite spr_player_walk_0;
extern const Sprite spr_player_walk_1;
extern const Sprite spr_bat0;
extern const Sprite spr_bat1;
extern const Sprite spr_spider;
extern const Sprite spr_snake_r;
extern const Sprite spr_miner;
extern const Sprite spr_dynamite;
extern const Sprite spr_explode;

#endif
