#!/usr/bin/env python3
"""
export_c64.py — Export game-rescue.json to C64 source files

Generates:
  - charset.c    : 1bpp charset data (256 tiles, 8 bytes each)
  - level_data.c : RLE level data with row offsets and entities
  - level_data.h : Level struct and externs

Usage: python3 export_c64.py <game-rescue.json> <output_dir>
"""

import json
import sys
import os


def convert_tile_2bpp_to_1bpp(tile_data):
    """Convert a GBC 2bpp tile (16 bytes) to C64 1bpp charset (8 bytes).
    Any non-zero pixel becomes a set bit."""
    result = []
    for row in range(8):
        lo = tile_data[row * 2]
        hi = tile_data[row * 2 + 1]
        result.append(lo | hi)  # merge planes: any color != 0 -> 1
    return result


def export_charset(proj, out_dir):
    """Export tileset as C64 charset (1bpp, 8 bytes per tile, 256 tiles max)."""
    tiles = proj["tileset"]
    count = min(len(tiles), 256)

    path_c = os.path.join(out_dir, "charset.c")
    path_h = os.path.join(out_dir, "charset.h")

    with open(path_c, "w") as fc, open(path_h, "w") as fh:
        fh.write("/* charset.h — Generated by export_c64.py */\n")
        fh.write("#ifndef CHARSET_H\n#define CHARSET_H\n\n")
        fh.write("#include <stdint.h>\n\n")
        fh.write(f"#define CHARSET_COUNT {count}\n")
        fh.write(f"extern const uint8_t charset_data[{count}][8];\n\n")
        fh.write("#endif\n")

        fc.write("/* charset.c — Generated by export_c64.py */\n")
        fc.write('#include "charset.h"\n\n')
        fc.write(f"const uint8_t charset_data[{count}][8] = {{\n")
        for i, tile in enumerate(tiles[:count]):
            c64_tile = convert_tile_2bpp_to_1bpp(tile)
            vals = ",".join(f"0x{b:02X}" for b in c64_tile)
            fc.write(f"    {{{vals}}},\n")
        fc.write("};\n")

    print(f"  charset: {count} tiles -> {path_c}")


def export_levels(proj, out_dir):
    """Export level data as RLE with row offsets and entities."""
    levels = proj["levels"]
    count = len(levels)

    path_c = os.path.join(out_dir, "level_data.c")
    path_h = os.path.join(out_dir, "level_data.h")

    with open(path_h, "w") as fh:
        fh.write("/* level_data.h — Generated by export_c64.py */\n")
        fh.write("#ifndef LEVEL_DATA_H\n#define LEVEL_DATA_H\n\n")
        fh.write("#include <stdint.h>\n\n")
        fh.write(f"#define NUM_LEVELS {count}\n\n")
        fh.write("typedef struct {\n")
        fh.write("    uint8_t width, height;\n")
        fh.write("    const uint8_t *rle;\n")
        fh.write("    const uint16_t *row_offsets;\n")
        fh.write("    uint8_t entity_count;\n")
        fh.write("    const uint8_t *entities;\n")
        fh.write("} LevelInfo;\n\n")
        fh.write("extern const LevelInfo levels[NUM_LEVELS];\n\n")
        for i in range(count):
            fh.write(f"extern const uint8_t level_{i}_rle[];\n")
            fh.write(f"extern const uint16_t level_{i}_row_offsets[];\n")
            fh.write(f"extern const uint8_t level_{i}_entities[];\n")
        fh.write("\n#endif\n")

    with open(path_c, "w") as fc:
        fc.write("/* level_data.c — Generated by export_c64.py */\n")
        fc.write('#include "level_data.h"\n\n')

        for li, lvl in enumerate(levels):
            w = lvl["width"]
            h = lvl["height"]
            tiles = lvl["tiles"]
            entities = lvl.get("entities", [])

            # RLE encode
            rle = []
            row_offsets = []
            for y in range(h):
                row_offsets.append(len(rle))
                row = tiles[y]
                x = 0
                while x < w:
                    t = row[x]
                    run = 1
                    while x + run < w and row[x + run] == t and run < 255:
                        run += 1
                    rle.append(run)
                    rle.append(t)
                    x += run

            # Write RLE
            fc.write(f"const uint8_t level_{li}_rle[] = {{\n    ")
            for i, b in enumerate(rle):
                fc.write(f"0x{b:02X}")
                if i < len(rle) - 1:
                    fc.write(",")
                if (i & 15) == 15:
                    fc.write("\n    ")
            fc.write("\n};\n")

            # Write row offsets
            fc.write(f"const uint16_t level_{li}_row_offsets[] = {{\n    ")
            for i, off in enumerate(row_offsets):
                fc.write(f"{off}")
                if i < len(row_offsets) - 1:
                    fc.write(",")
                if (i & 15) == 15:
                    fc.write("\n    ")
            fc.write("\n};\n")

            # Write entities
            fc.write(f"const uint8_t level_{li}_entities[] = {{\n    ")
            if entities:
                for i, ent in enumerate(entities):
                    fc.write(f"{ent['x']},{ent['y']},{ent['type']},{ent.get('vx', 1)}")
                    if i < len(entities) - 1:
                        fc.write(", ")
            else:
                fc.write("0")
            fc.write("\n};\n\n")

            print(f"  Level {li}: {w}x{h}, {len(rle)} bytes RLE, {len(entities)} entities")

        # Write level info table
        fc.write(f"const LevelInfo levels[NUM_LEVELS] = {{\n")
        for li, lvl in enumerate(levels):
            ent_count = len(lvl.get("entities", []))
            fc.write(f"    {{{lvl['width']}, {lvl['height']}, "
                     f"level_{li}_rle, level_{li}_row_offsets, "
                     f"{ent_count}, level_{li}_entities}}")
            if li < count - 1:
                fc.write(",")
            fc.write("\n")
        fc.write("};\n")

    print(f"  levels: {count} levels -> {path_c}")


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <game-rescue.json> <output_dir>")
        sys.exit(1)

    json_path = sys.argv[1]
    out_dir = sys.argv[2]

    with open(json_path) as f:
        proj = json.load(f)

    os.makedirs(out_dir, exist_ok=True)

    print(f"Exporting {json_path} -> {out_dir}/")
    export_charset(proj, out_dir)
    export_levels(proj, out_dir)
    print("Done.")


if __name__ == "__main__":
    main()
