/*
 * export.c — C code export for sprites, palettes, and level data
 */
#include "app.h"
#include <stdio.h>
#include <string.h>

#define BANK_SIZE 14000  /* headroom in 16KB bank for linker overhead */

void export_sprites(App *app, const char *dir) {
    char c_path[512], h_path[512];
    snprintf(c_path, sizeof(c_path), "%s/sprites_export.c", dir);
    snprintf(h_path, sizeof(h_path), "%s/sprites_export.h", dir);

    FILE *fc = fopen(c_path, "w");
    FILE *fh = fopen(h_path, "w");
    if (!fc || !fh) { if (fc) fclose(fc); if (fh) fclose(fh); return; }

    fprintf(fc, "/* sprites_export.c — Generated by GBC Workbench */\n");
    fprintf(fc, "#include \"sprites_export.h\"\n\n");
    fprintf(fh, "/* sprites_export.h — Generated by GBC Workbench */\n");
    fprintf(fh, "#ifndef SPRITES_EXPORT_H\n#define SPRITES_EXPORT_H\n\n");
    fprintf(fh, "#include <stdint.h>\n\n");
    fprintf(fh, "#define EXPORT_SPRITE_COUNT %d\n\n", app->sprite_count);

    for (int i = 0; i < app->sprite_count; i++) {
        GBCTile *spr = &app->sprites[i];
        fprintf(fc, "const uint8_t spr_%s[32] = {\n", spr->name);
        for (int row = 0; row < 16; row++) {
            fprintf(fc, "    0x%02X,0x%02X,\n",
                    spr->data[row * 2], spr->data[row * 2 + 1]);
        }
        fprintf(fc, "};\n\n");
        fprintf(fh, "extern const uint8_t spr_%s[32];\n", spr->name);
    }

    fprintf(fh, "\n#endif\n");
    fclose(fc); fclose(fh);
    app_log_info(app, "Exported %d sprites to %s", app->sprite_count, c_path);
}

void export_palettes(App *app, const char *dir) {
    char c_path[512], h_path[512];
    snprintf(c_path, sizeof(c_path), "%s/palettes_export.c", dir);
    snprintf(h_path, sizeof(h_path), "%s/palettes_export.h", dir);

    FILE *fc = fopen(c_path, "w");
    FILE *fh = fopen(h_path, "w");
    if (!fc || !fh) { if (fc) fclose(fc); if (fh) fclose(fh); return; }

    fprintf(fc, "/* palettes_export.c — Generated by GBC Workbench */\n");
    fprintf(fc, "#include \"palettes_export.h\"\n\n");
    fprintf(fh, "/* palettes_export.h — Generated by GBC Workbench */\n");
    fprintf(fh, "#ifndef PALETTES_EXPORT_H\n#define PALETTES_EXPORT_H\n\n");
    fprintf(fh, "#include <stdint.h>\n\n");

    /* BG palettes: RGB555 format matching GBC hardware */
    fprintf(fh, "#define EXPORT_BG_PAL_COUNT %d\n", MAX_BG_PALS);
    fprintf(fh, "#define EXPORT_SPR_PAL_COUNT %d\n\n", MAX_SPR_PALS);
    fprintf(fh, "extern const uint16_t exported_bg_palettes[%d];\n", MAX_BG_PALS * COLORS_PER_PAL);
    fprintf(fh, "extern const uint16_t exported_spr_palettes[%d];\n", MAX_SPR_PALS * COLORS_PER_PAL);

    fprintf(fc, "const uint16_t exported_bg_palettes[%d] = {\n", MAX_BG_PALS * COLORS_PER_PAL);
    for (int i = 0; i < MAX_BG_PALS; i++) {
        fprintf(fc, "    /* BG palette %d */\n    ", i);
        for (int c = 0; c < COLORS_PER_PAL; c++) {
            RGB5 rgb = app->tmap.bg_pals[i].colors[c];
            fprintf(fc, "(%d | (%d<<5) | (%d<<10))",
                    rgb.r, rgb.g, rgb.b);
            if (i < MAX_BG_PALS - 1 || c < COLORS_PER_PAL - 1)
                fprintf(fc, ", ");
        }
        fprintf(fc, "\n");
    }
    fprintf(fc, "};\n\n");

    fprintf(fc, "const uint16_t exported_spr_palettes[%d] = {\n", MAX_SPR_PALS * COLORS_PER_PAL);
    for (int i = 0; i < MAX_SPR_PALS; i++) {
        fprintf(fc, "    /* Sprite palette %d */\n    ", i);
        for (int c = 0; c < COLORS_PER_PAL; c++) {
            RGB5 rgb = app->tmap.spr_pals[i].colors[c];
            fprintf(fc, "(%d | (%d<<5) | (%d<<10))",
                    rgb.r, rgb.g, rgb.b);
            if (i < MAX_SPR_PALS - 1 || c < COLORS_PER_PAL - 1)
                fprintf(fc, ", ");
        }
        fprintf(fc, "\n");
    }
    fprintf(fc, "};\n");

    fprintf(fh, "\n#endif\n");
    fclose(fc); fclose(fh);
    app_log_info(app, "Exported %d BG + %d sprite palettes to %s",
                 MAX_BG_PALS, MAX_SPR_PALS, c_path);
}

void export_levels(App *app, const char *dir) {
    char c_path[512], h_path[512], m_path[512];
    snprintf(c_path, sizeof(c_path), "%s/level_data.c", dir);
    snprintf(h_path, sizeof(h_path), "%s/level_data.h", dir);
    snprintf(m_path, sizeof(m_path), "%s/levels_meta.c", dir);

    FILE *fc = fopen(c_path, "w");
    FILE *fh = fopen(h_path, "w");
    if (!fc || !fh) { if (fc) fclose(fc); if (fh) fclose(fh); return; }

    int lc = app->tmap.level_count;

    /* Header */
    fprintf(fh, "// level_data.h — Generated by GBC Workbench\n");
    fprintf(fh, "#ifndef LEVEL_DATA_H\n#define LEVEL_DATA_H\n\n");
    fprintf(fh, "#include <stdint.h>\n\n");
    fprintf(fh, "#define NUM_LEVELS %d\n\n", lc);
    fprintf(fh, "typedef struct {\n");
    fprintf(fh, "    uint8_t width, height;\n");
    fprintf(fh, "    uint8_t bank;\n");
    fprintf(fh, "    const uint8_t *rle;\n");
    fprintf(fh, "    const uint16_t *row_offsets;\n");
    fprintf(fh, "    uint8_t entity_count;\n");
    fprintf(fh, "    const uint8_t *entities;\n");
    fprintf(fh, "} LevelInfo;\n\n");
    fprintf(fh, "extern const LevelInfo levels[NUM_LEVELS];\n\n");
    fprintf(fh, "#include <gb/gb.h>\n\n");
    for (int li = 0; li < lc; li++) {
        fprintf(fh, "extern const uint8_t level_%d_rle[];\n", li);
        fprintf(fh, "extern const uint16_t level_%d_row_offsets[];\n", li);
        fprintf(fh, "extern const uint8_t level_%d_entities[];\n", li);
    }
    fprintf(fh, "\n#endif\n");
    fclose(fh);

    /* RLE encode + compute banking */
    static uint8_t rle_bufs[TMAP_MAX_LEVELS][65536];
    static uint16_t row_offs[TMAP_MAX_LEVELS][TMAP_MAX_H];
    int rle_sizes[TMAP_MAX_LEVELS];
    int level_banks[TMAP_MAX_LEVELS];
    int cur_bank = 1, bank_used = 0;

    for (int li = 0; li < lc; li++) {
        TilemapLevel *lvl = &app->tmap.levels[li];
        int rle_pos = 0;
        for (int y = 0; y < lvl->height; y++) {
            row_offs[li][y] = (uint16_t)rle_pos;
            int x = 0;
            while (x < lvl->width) {
                uint8_t t = lvl->tiles[y][x];
                int run = 1;
                while (x + run < lvl->width &&
                       lvl->tiles[y][x + run] == t && run < 255)
                    run++;
                rle_bufs[li][rle_pos++] = (uint8_t)run;
                rle_bufs[li][rle_pos++] = t;
                x += run;
            }
        }
        rle_sizes[li] = rle_pos;

        int sz = rle_pos + lvl->height * 2 + lvl->entity_count * 4 + 16;
        if (bank_used + sz > BANK_SIZE && bank_used > 0) {
            cur_bank++;
            bank_used = 0;
        }
        level_banks[li] = cur_bank;
        bank_used += sz;
    }

    /* Write banked level data — all in bank 1, linker handles overflow */
    fprintf(fc, "// level_data.c — Generated by GBC Workbench\n\n");
    fprintf(fc, "#include \"level_data.h\"\n");
    fprintf(fc, "#include <gb/gb.h>\n\n");
    fprintf(fc, "#pragma bank 1\n\n");

    for (int li = 0; li < lc; li++) {
        TilemapLevel *lvl = &app->tmap.levels[li];

        /* RLE data */
        fprintf(fc, "BANKREF(level_%d_rle)\n", li);
        fprintf(fc, "const uint8_t level_%d_rle[] = {\n    ", li);
        for (int i = 0; i < rle_sizes[li]; i++) {
            fprintf(fc, "0x%02X%s", rle_bufs[li][i],
                    i < rle_sizes[li] - 1 ? "," : "");
            if ((i & 15) == 15) fprintf(fc, "\n    ");
        }
        fprintf(fc, "\n};\n");

        /* Row offsets */
        fprintf(fc, "BANKREF(level_%d_row_offsets)\n", li);
        fprintf(fc, "const uint16_t level_%d_row_offsets[] = {\n    ", li);
        for (int y = 0; y < lvl->height; y++) {
            fprintf(fc, "%d%s", row_offs[li][y],
                    y < lvl->height - 1 ? "," : "");
            if ((y & 15) == 15) fprintf(fc, "\n    ");
        }
        fprintf(fc, "\n};\n");

        /* Entities */
        fprintf(fc, "BANKREF(level_%d_entities)\n", li);
        fprintf(fc, "const uint8_t level_%d_entities[] = {\n    ", li);
        for (int i = 0; i < lvl->entity_count; i++) {
            TilemapEntity *e = &lvl->entities[i];
            fprintf(fc, "%d,%d,%d,%d%s",
                    e->x, e->y, e->type, (uint8_t)e->vx,
                    i < lvl->entity_count - 1 ? ", " : "");
        }
        if (lvl->entity_count == 0) fprintf(fc, "0");
        fprintf(fc, "\n};\n\n");

        app_log_dbg(app, "Level %d: %d bytes RLE, %d ent, bank %d",
                    li, rle_sizes[li], lvl->entity_count, level_banks[li]);
    }
    fclose(fc);

    /* levels_meta.c — fixed ROM (no #pragma bank) */
    FILE *fm = fopen(m_path, "w");
    if (fm) {
        fprintf(fm, "// levels_meta.c — Generated by GBC Workbench\n");
        fprintf(fm, "#include \"level_data.h\"\n\n");
        fprintf(fm, "const LevelInfo levels[NUM_LEVELS] = {\n");
        for (int li = 0; li < lc; li++) {
            TilemapLevel *lvl = &app->tmap.levels[li];
            fprintf(fm, "    {%d, %d, 1, level_%d_rle, "
                    "level_%d_row_offsets, %d, level_%d_entities}%s\n",
                    lvl->width, lvl->height,
                    li, li, lvl->entity_count, li,
                    li < lc - 1 ? "," : "");
        }
        fprintf(fm, "};\n");
        fclose(fm);
    }

    app_log_info(app, "Exported %d levels (banks 1-%d) to %s", lc, cur_bank, c_path);
}
