/*
 * export.c — C code export for sprites and palettes
 */
#include "app.h"
#include <stdio.h>
#include <string.h>

void export_sprites(App *app, const char *dir) {
    char c_path[512], h_path[512];
    snprintf(c_path, sizeof(c_path), "%s/sprites_export.c", dir);
    snprintf(h_path, sizeof(h_path), "%s/sprites_export.h", dir);

    FILE *fc = fopen(c_path, "w");
    FILE *fh = fopen(h_path, "w");
    if (!fc || !fh) { if (fc) fclose(fc); if (fh) fclose(fh); return; }

    fprintf(fc, "/* sprites_export.c — Generated by GBC Workbench */\n");
    fprintf(fc, "#include \"sprites_export.h\"\n\n");
    fprintf(fh, "/* sprites_export.h — Generated by GBC Workbench */\n");
    fprintf(fh, "#ifndef SPRITES_EXPORT_H\n#define SPRITES_EXPORT_H\n\n");
    fprintf(fh, "#include <stdint.h>\n\n");
    fprintf(fh, "#define EXPORT_SPRITE_COUNT %d\n\n", app->sprite_count);

    for (int i = 0; i < app->sprite_count; i++) {
        GBCTile *spr = &app->sprites[i];
        fprintf(fc, "const uint8_t spr_%s[32] = {\n", spr->name);
        for (int row = 0; row < 16; row++) {
            fprintf(fc, "    0x%02X,0x%02X,\n",
                    spr->data[row * 2], spr->data[row * 2 + 1]);
        }
        fprintf(fc, "};\n\n");
        fprintf(fh, "extern const uint8_t spr_%s[32];\n", spr->name);
    }

    fprintf(fh, "\n#endif\n");
    fclose(fc); fclose(fh);
    app_log_info(app, "Exported %d sprites", app->sprite_count);
}

void export_palettes(App *app, const char *dir) {
    char c_path[512], h_path[512];
    snprintf(c_path, sizeof(c_path), "%s/palettes_export.c", dir);
    snprintf(h_path, sizeof(h_path), "%s/palettes_export.h", dir);

    FILE *fc = fopen(c_path, "w");
    FILE *fh = fopen(h_path, "w");
    if (!fc || !fh) { if (fc) fclose(fc); if (fh) fclose(fh); return; }

    fprintf(fc, "/* palettes_export.c — Generated by GBC Workbench */\n");
    fprintf(fc, "#include \"palettes_export.h\"\n\n");
    fprintf(fh, "/* palettes_export.h — Generated by GBC Workbench */\n");
    fprintf(fh, "#ifndef PALETTES_EXPORT_H\n#define PALETTES_EXPORT_H\n\n");
    fprintf(fh, "#include <stdint.h>\n\n");

    /* BG palettes: RGB555 format matching GBC hardware */
    fprintf(fh, "#define EXPORT_BG_PAL_COUNT %d\n", MAX_BG_PALS);
    fprintf(fh, "#define EXPORT_SPR_PAL_COUNT %d\n\n", MAX_SPR_PALS);
    fprintf(fh, "extern const uint16_t exported_bg_palettes[%d];\n", MAX_BG_PALS * COLORS_PER_PAL);
    fprintf(fh, "extern const uint16_t exported_spr_palettes[%d];\n", MAX_SPR_PALS * COLORS_PER_PAL);

    fprintf(fc, "const uint16_t exported_bg_palettes[%d] = {\n", MAX_BG_PALS * COLORS_PER_PAL);
    for (int i = 0; i < MAX_BG_PALS; i++) {
        fprintf(fc, "    /* BG palette %d */\n    ", i);
        for (int c = 0; c < COLORS_PER_PAL; c++) {
            RGB5 rgb = app->tmap.bg_pals[i].colors[c];
            fprintf(fc, "(%d | (%d<<5) | (%d<<10))",
                    rgb.r, rgb.g, rgb.b);
            if (i < MAX_BG_PALS - 1 || c < COLORS_PER_PAL - 1)
                fprintf(fc, ", ");
        }
        fprintf(fc, "\n");
    }
    fprintf(fc, "};\n\n");

    fprintf(fc, "const uint16_t exported_spr_palettes[%d] = {\n", MAX_SPR_PALS * COLORS_PER_PAL);
    for (int i = 0; i < MAX_SPR_PALS; i++) {
        fprintf(fc, "    /* Sprite palette %d */\n    ", i);
        for (int c = 0; c < COLORS_PER_PAL; c++) {
            RGB5 rgb = app->tmap.spr_pals[i].colors[c];
            fprintf(fc, "(%d | (%d<<5) | (%d<<10))",
                    rgb.r, rgb.g, rgb.b);
            if (i < MAX_SPR_PALS - 1 || c < COLORS_PER_PAL - 1)
                fprintf(fc, ", ");
        }
        fprintf(fc, "\n");
    }
    fprintf(fc, "};\n");

    fprintf(fh, "\n#endif\n");
    fclose(fc); fclose(fh);
    app_log_info(app, "Exported %d BG + %d sprite palettes",
                 MAX_BG_PALS, MAX_SPR_PALS);
}
