/*
 * file_io.c — JSON load/save, C export, level conversion
 */
#include "app.h"
#include "native_macos.h"
#include "json.h"
#include "project_io.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

void app_new_project(App *app) {
    app->sprite_count = 0;
    app->cur_sprite = 0;
    tilemap_project_init(&app->tmap);
    app->cur_level = 0;
    app->project_path[0] = 0;
    app->modified = false;
    app_log_info(app, "New project");
}

void app_load_project(App *app, const char *path) {
    /* TODO: JSON load for tilemap project */
    app_log_info(app, "Load not yet implemented: %s", path);
}

void app_save_project(App *app, const char *path) {
    if (path) strncpy(app->project_path, path, sizeof(app->project_path) - 1);
    if (!app->project_path[0]) { app_save_project_as(app); return; }

    FILE *f = fopen(app->project_path, "w");
    if (!f) { app_log_err(app, "Cannot write %s", app->project_path); return; }

    fprintf(f, "{\n");

    /* Tileset */
    fprintf(f, "  \"tileset\": [\n");
    for (int i = 0; i < app->tmap.tileset.used_count; i++) {
        fprintf(f, "    [");
        for (int j = 0; j < 16; j++)
            fprintf(f, "%d%s", app->tmap.tileset.entries[i].data[j], j < 15 ? "," : "");
        fprintf(f, "]%s\n", i < app->tmap.tileset.used_count - 1 ? "," : "");
    }
    fprintf(f, "  ],\n");

    /* Levels */
    fprintf(f, "  \"levels\": [\n");
    for (int li = 0; li < app->tmap.level_count; li++) {
        TilemapLevel *lvl = &app->tmap.levels[li];
        fprintf(f, "    {\n");
        fprintf(f, "      \"name\": \"%s\",\n", lvl->name);
        fprintf(f, "      \"width\": %d,\n", lvl->width);
        fprintf(f, "      \"height\": %d,\n", lvl->height);
        /* Tiles as rows of comma-separated indices */
        fprintf(f, "      \"tiles\": [\n");
        for (int y = 0; y < lvl->height; y++) {
            fprintf(f, "        [");
            for (int x = 0; x < lvl->width; x++)
                fprintf(f, "%d%s", lvl->tiles[y][x], x < lvl->width - 1 ? "," : "");
            fprintf(f, "]%s\n", y < lvl->height - 1 ? "," : "");
        }
        fprintf(f, "      ],\n");
        /* Entities */
        fprintf(f, "      \"entities\": [\n");
        for (int i = 0; i < lvl->entity_count; i++) {
            TilemapEntity *e = &lvl->entities[i];
            fprintf(f, "        {\"x\":%d,\"y\":%d,\"type\":%d,\"vx\":%d}%s\n",
                    e->x, e->y, e->type, e->vx, i < lvl->entity_count - 1 ? "," : "");
        }
        fprintf(f, "      ]\n");
        fprintf(f, "    }%s\n", li < app->tmap.level_count - 1 ? "," : "");
    }
    fprintf(f, "  ]\n");

    fprintf(f, "}\n");
    fclose(f);
    app->modified = false;
    app_log_info(app, "Saved: %s (%d levels)", app->project_path, app->tmap.level_count);
}

void app_open_project(App *app) {
    char *p = dialog_open_file("Open Project", "json");
    if (p) { app_load_project(app, p); free(p); }
}

void app_save_project_as(App *app) {
    char *p = dialog_save_file("Save Project", "tilemap.json");
    if (p) { app_save_project(app, p); free(p); }
}

void app_export_c(App *app) {
    char *dir = dialog_open_folder("Export to directory");
    if (!dir) return;

    char c_path[512], h_path[512];
    snprintf(c_path, sizeof(c_path), "%s/levels_export.c", dir);
    snprintf(h_path, sizeof(h_path), "%s/levels_export.h", dir);

    FILE *fc = fopen(c_path, "w");
    FILE *fh = fopen(h_path, "w");
    if (!fc || !fh) { if (fc) fclose(fc); if (fh) fclose(fh); free(dir); return; }

    fprintf(fc, "/* levels_export.c — Generated by GBC Studio */\n");
    fprintf(fc, "#include \"levels_export.h\"\n\n");
    fprintf(fh, "/* levels_export.h — Generated by GBC Studio */\n");
    fprintf(fh, "#ifndef LEVELS_EXPORT_H\n#define LEVELS_EXPORT_H\n\n");
    fprintf(fh, "#include <stdint.h>\n\n");

    /* Export tileset */
    fprintf(fc, "const uint8_t tileset_data[%d][16] = {\n", app->tmap.tileset.used_count);
    for (int i = 0; i < app->tmap.tileset.used_count; i++) {
        fprintf(fc, "    {");
        for (int j = 0; j < 16; j++)
            fprintf(fc, "0x%02X%s", app->tmap.tileset.entries[i].data[j], j < 15 ? "," : "");
        fprintf(fc, "},\n");
    }
    fprintf(fc, "};\n\n");

    /* Export levels as RLE */
    for (int li = 0; li < app->tmap.level_count; li++) {
        TilemapLevel *lvl = &app->tmap.levels[li];
        fprintf(fc, "/* %s (%dx%d) */\n", lvl->name, lvl->width, lvl->height);
        fprintf(fc, "const uint8_t level_%d_rle[] = {\n    ", li);
        int bytes = 0;
        for (int y = 0; y < lvl->height; y++) {
            int x = 0;
            while (x < lvl->width) {
                uint8_t t = lvl->tiles[y][x];
                int run = 1;
                while (x + run < lvl->width && lvl->tiles[y][x + run] == t && run < 255) run++;
                fprintf(fc, "%d,%d, ", run, t);
                bytes += 2;
                x += run;
            }
        }
        fprintf(fc, "\n};\n\n");
        fprintf(fh, "#define LEVEL_%d_W %d\n", li, lvl->width);
        fprintf(fh, "#define LEVEL_%d_H %d\n", li, lvl->height);
        fprintf(fh, "extern const uint8_t level_%d_rle[];\n\n", li);
        app_log_dbg(app, "Level %d: %dx%d → %d bytes RLE", li, lvl->width, lvl->height, bytes);
    }

    fprintf(fh, "\n#endif\n");
    fclose(fc); fclose(fh);
    app_log_info(app, "Exported %d levels to %s", app->tmap.level_count, dir);
    free(dir);
}

/* ── Convert hero.json levels to tilemaps ─────────────────── */

/* Same rasterize logic as panel_room_editor.c */
#define GRID_W 20
#define GRID_H 16
#define CELL_EMPTY 0
#define CELL_BORDER 1
#define CELL_SOLID 2

static int tc(int gx) { return (int)(((unsigned)((unsigned char)(gx+128))*20)>>8); }
static int tr(int gy) { int v=(int)(((unsigned)(50-gy)*39)>>8); return v<0?0:v>=GRID_H?GRID_H-1:v; }

static void tl(uint8_t g[GRID_H][GRID_W], int x1,int y1,int x2,int y2) {
    int c1=tc(x1),r1=tr(y1),c2=tc(x2),r2=tr(y2);
    int dx=abs(c2-c1),dy=abs(r2-r1),sx=c1<c2?1:-1,sy=r1<r2?1:-1,err=dx-dy;
    for(;;) {
        if(r1>=0&&r1<GRID_H&&c1>=0&&c1<GRID_W) g[r1][c1]=CELL_BORDER;
        if(c1==c2&&r1==r2) break;
        int e2=2*err;
        if(e2>-dy){err-=dy;c1+=sx;}
        if(e2<dx){err+=dx;r1+=sy;}
    }
}

static void ff(uint8_t g[GRID_H][GRID_W],int sr,int sc) {
    if(sr<0||sr>=GRID_H||sc<0||sc>=GRID_W) return;
    g[sr][sc]=CELL_EMPTY;
    int ch=1; while(ch){ch=0;
        for(int r=0;r<GRID_H;r++) for(int c=0;c<GRID_W;c++){
            if(g[r][c]!=CELL_SOLID) continue;
            if((r>0&&g[r-1][c]==CELL_EMPTY)||(r<GRID_H-1&&g[r+1][c]==CELL_EMPTY)||
               (c>0&&g[r][c-1]==CELL_EMPTY)||(c<GRID_W-1&&g[r][c+1]==CELL_EMPTY))
                {g[r][c]=CELL_EMPTY;ch=1;}
        }
    }
}

void app_convert_levels(App *app, const char *hero_json_path) {
    FILE *f = fopen(hero_json_path, "r");
    if (!f) { app_log_err(app, "Cannot open %s", hero_json_path); return; }
    fseek(f, 0, SEEK_END); long len = ftell(f); fseek(f, 0, SEEK_SET);
    char *json = malloc(len + 1); fread(json, 1, len, f); json[len] = 0; fclose(f);

    Project proj;
    project_init(&proj);
    project_parse_json(json, &proj);
    free(json);

    app_log_info(app, "Converting %d levels...", proj.level_count);

    /* Ensure tileset has basic tiles */
    /* 0=empty, 1=solid rock, 2=border */
    if (app->tmap.tileset.used_count < 3) app->tmap.tileset.used_count = 3;

    app->tmap.level_count = proj.level_count;
    int yoff[] = {20, -10, -40};

    for (int li = 0; li < proj.level_count; li++) {
        Level *lvl = &proj.levels[li];

        /* BFS from room 0 using exits to compute grid positions */
        int gx[MAX_ROOMS], gy[MAX_ROOMS];
        int placed[MAX_ROOMS];
        memset(placed, 0, sizeof(placed));
        memset(gx, 0, sizeof(gx)); memset(gy, 0, sizeof(gy));

        if (lvl->room_count > 0) {
            placed[0] = 1;
            int queue[MAX_ROOMS], qh = 0, qt = 0;
            queue[qt++] = 0;
            while (qh < qt) {
                int ri = queue[qh++];
                Room *r = &lvl->rooms[ri];
                struct { int target; int dx; int dy; } exits[] = {
                    {r->exit_right,  1,  0},
                    {r->exit_left,  -1,  0},
                    {r->exit_top,    0, -1},
                    {r->exit_bottom, 0,  1},
                };
                for (int e = 0; e < 4; e++) {
                    if (exits[e].target < 0) continue;
                    int ti = exits[e].target - 1; /* 1-based to 0-based */
                    if (ti < 0 || ti >= lvl->room_count || placed[ti]) continue;
                    placed[ti] = 1;
                    gx[ti] = gx[ri] + exits[e].dx;
                    gy[ti] = gy[ri] + exits[e].dy;
                    queue[qt++] = ti;
                }
            }
            /* Place unreachable rooms */
            int max_gy = 0;
            for (int i = 0; i < lvl->room_count; i++)
                if (placed[i] && gy[i] > max_gy) max_gy = gy[i];
            int col = 0;
            for (int i = 0; i < lvl->room_count; i++) {
                if (!placed[i]) { placed[i] = 1; gx[i] = col++; gy[i] = max_gy + 2; }
            }
        }

        /* Normalize so min is (0,0) */
        int min_gx = 0, min_gy = 0;
        for (int i = 0; i < lvl->room_count; i++) {
            if (gx[i] < min_gx) min_gx = gx[i];
            if (gy[i] < min_gy) min_gy = gy[i];
        }
        int max_gx = 0, max_gy = 0;
        for (int i = 0; i < lvl->room_count; i++) {
            gx[i] -= min_gx; gy[i] -= min_gy;
            if (gx[i] > max_gx) max_gx = gx[i];
            if (gy[i] > max_gy) max_gy = gy[i];
        }

        TilemapLevel *tm = &app->tmap.levels[li];
        memset(tm, 0, sizeof(*tm));
        strncpy(tm->name, lvl->name, sizeof(tm->name) - 1);
        tm->width = (max_gx + 1) * GRID_W;
        tm->height = (max_gy + 1) * GRID_H;
        if (tm->width > TMAP_MAX_W) tm->width = TMAP_MAX_W;
        if (tm->height > TMAP_MAX_H) tm->height = TMAP_MAX_H;

        /* Fill with solid */
        memset(tm->tiles, 1, sizeof(tm->tiles));

        for (int ri = 0; ri < lvl->room_count; ri++) {
            Room *room = &lvl->rooms[ri];
            int ox = gx[ri] * GRID_W, oy = gy[ri] * GRID_H;

            /* Build room grid */
            uint8_t grid[GRID_H][GRID_W];
            memset(grid, CELL_SOLID, sizeof(grid));
            for (int rri = 0; rri < 3; rri++) {
                int rt_idx = room->rows[rri];
                if (rt_idx < 0 || rt_idx >= proj.row_type_count) continue;
                RowType *rt = &proj.row_types[rt_idx];
                for (int pi = 0; pi < rt->cave_line_count; pi++) {
                    Polyline *pl = &rt->cave_lines[pi];
                    for (int j = 1; j < pl->count; j++)
                        tl(grid, pl->points[j-1].x, pl->points[j-1].y+yoff[rri],
                                 pl->points[j].x, pl->points[j].y+yoff[rri]);
                }
            }
            /* Flood fill: use player_start if available, else find a cell
               adjacent to a border that is still solid (inside the cave) */
            if (room->has_player_start) {
                ff(grid, tr(room->player_start.y), tc(room->player_start.x));
            } else {
                /* Find first solid cell next to a border — that's inside the cave */
                int found = 0;
                for (int r = 1; r < GRID_H - 1 && !found; r++) {
                    for (int c2 = 1; c2 < GRID_W - 1 && !found; c2++) {
                        if (grid[r][c2] == CELL_SOLID &&
                            (grid[r-1][c2] == CELL_BORDER || grid[r+1][c2] == CELL_BORDER ||
                             grid[r][c2-1] == CELL_BORDER || grid[r][c2+1] == CELL_BORDER)) {
                            ff(grid, r, c2);
                            found = 1;
                        }
                    }
                }
            }

            /* Copy to tilemap */
            for (int r = 0; r < GRID_H; r++) {
                for (int c = 0; c < GRID_W; c++) {
                    int tx = ox + c, ty = oy + r;
                    if (tx >= tm->width || ty >= tm->height) continue;
                    switch (grid[r][c]) {
                    case CELL_EMPTY:  tm->tiles[ty][tx] = 0; break;
                    case CELL_BORDER: tm->tiles[ty][tx] = 2; break;
                    default:          tm->tiles[ty][tx] = 1; break;
                    }
                }
            }
        }

        app_log_dbg(app, "Level %d: %s → %dx%d tilemap (%d rooms)", li, lvl->name, tm->width, tm->height, lvl->room_count);
    }

    app->cur_level = 0;
    app->modified = true;
    app_log_info(app, "Converted %d levels to tilemaps", proj.level_count);
}
