/*
 * file_io.c — JSON load/save, C export for GBC tiles and palettes
 */
#include "app.h"
#include "native_macos.h"
#include "json.h"
#include "project_io.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

void app_new_project(App *app) {
    app->tile_count = 0;
    app->cur_tile = 0;
    app->project_path[0] = 0;
    app->modified = false;
    app_log_info(app, "New project");
}

void app_load_project(App *app, const char *path) {
    /* TODO: JSON load for tile data */
    app_log_info(app, "Load not yet implemented: %s", path);
}

void app_save_project(App *app, const char *path) {
    if (path) strncpy(app->project_path, path, sizeof(app->project_path) - 1);
    if (!app->project_path[0]) { app_save_project_as(app); return; }
    /* TODO: JSON save for tile data */
    app_log_info(app, "Save not yet implemented");
}

void app_open_project(App *app) {
    char *p = dialog_open_file("Open Project", "json");
    if (p) { app_load_project(app, p); free(p); }
}

void app_save_project_as(App *app) {
    char *p = dialog_save_file("Save Project", "tiles.json");
    if (p) { app_save_project(app, p); free(p); }
}

void app_export_c(App *app) {
    char *dir = dialog_open_folder("Export to directory");
    if (!dir) return;

    char c_path[512], h_path[512];
    snprintf(c_path, sizeof(c_path), "%s/tiles_export.c", dir);
    snprintf(h_path, sizeof(h_path), "%s/tiles_export.h", dir);

    FILE *fc = fopen(c_path, "w");
    FILE *fh = fopen(h_path, "w");
    if (!fc || !fh) { if (fc) fclose(fc); if (fh) fclose(fh); free(dir); return; }

    fprintf(fc, "/* tiles_export.c — Generated by GBC Studio */\n");
    fprintf(fc, "#include \"tiles_export.h\"\n\n");
    fprintf(fh, "/* tiles_export.h — Generated by GBC Studio */\n");
    fprintf(fh, "#ifndef TILES_EXPORT_H\n#define TILES_EXPORT_H\n\n");
    fprintf(fh, "#include <stdint.h>\n\n");

    /* Export sprite palettes */
    fprintf(fc, "const uint16_t spr_palettes_export[] = {\n");
    for (int pi = 0; pi < MAX_SPR_PALS; pi++) {
        fprintf(fc, "    /* PAL %d */ ", pi);
        for (int ci = 0; ci < COLORS_PER_PAL; ci++) {
            RGB5 c = app->spr_pals[pi].colors[ci];
            uint16_t rgb555 = (c.b << 10) | (c.g << 5) | c.r;
            fprintf(fc, "0x%04X, ", rgb555);
        }
        fprintf(fc, "\n");
    }
    fprintf(fc, "};\n\n");

    /* Export tiles */
    for (int i = 0; i < app->tile_count; i++) {
        GBCTile *t = &app->tiles[i];
        fprintf(fc, "static const uint8_t spr_%s[] = {\n    ", t->name);
        for (int j = 0; j < TILE_BYTES; j++) {
            fprintf(fc, "0x%02X,", t->data[j]);
            if (j % 16 == 15) fprintf(fc, "\n    ");
        }
        fprintf(fc, "\n};\n\n");
        fprintf(fh, "extern const uint8_t spr_%s[%d];\n", t->name, TILE_BYTES);
    }

    fprintf(fh, "\n#endif\n");
    fclose(fc); fclose(fh);
    app_log_info(app, "Exported %d tiles to %s", app->tile_count, dir);
    free(dir);
}

void app_import_tiles_c(App *app, const char *path) {
    app_log_info(app, "Import not yet implemented: %s", path);
}

void app_load_levels(App *app, const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) { app_log_err(app, "Cannot open %s", path); return; }
    fseek(f, 0, SEEK_END); long len = ftell(f); fseek(f, 0, SEEK_SET);
    char *json = malloc(len + 1); fread(json, 1, len, f); json[len] = 0; fclose(f);

    project_init(&app->level_project);
    int n = project_parse_json(json, &app->level_project);
    free(json);

    app->cur_level = 0;
    app->cur_room = app->level_project.levels[0].room_count > 0 ? 0 : -1;
    app->cur_row_type = 0;
    app_log_info(app, "Levels loaded: %s (%d levels)", path, n);
}
