#!/usr/bin/env python3
"""
export_md.py -- Export game-rescue.json to Mega Drive / SGDK source files

Generates:
  - level_data.c/h : RLE level data (same format, SGDK types)
  - tileset_md.c   : 4bpp tile data for VDP upload

Usage: python3 export_md.py <game-rescue.json> <output_dir> [--max-levels N]
"""

import json
import sys
import os


def convert_tile_2bpp_to_4bpp(tile_data):
    """Convert GBC 2bpp tile (16 bytes) to MD 4bpp (32 bytes / 8 u32 words).
    Each pixel becomes a 4-bit nibble. GBC color 0-3 maps to MD color 0-3."""
    words = []
    for row in range(8):
        lo = tile_data[row * 2]
        hi = tile_data[row * 2 + 1]
        word = 0
        for bit in range(8):
            shift = 7 - bit
            ci = ((lo >> shift) & 1) | (((hi >> shift) & 1) << 1)
            word |= ci << ((7 - bit) * 4)
        words.append(word)
    return words


def export_tileset(proj, out_dir):
    """Export tileset as MD 4bpp format."""
    tiles = proj["tileset"]
    count = min(len(tiles), 256)
    path = os.path.join(out_dir, "tileset_md.c")

    with open(path, "w") as f:
        f.write("/* tileset_md.c -- Generated by export_md.py */\n")
        f.write('#include <genesis.h>\n\n')
        f.write(f"const u32 md_tileset[{count}][8] = {{\n")
        for i, tile in enumerate(tiles[:count]):
            words = convert_tile_2bpp_to_4bpp(tile)
            vals = ",".join(f"0x{w:08X}" for w in words)
            f.write(f"    {{{vals}}},\n")
        f.write("};\n")

    print(f"  tileset: {count} tiles -> {path}")


def export_levels(proj, out_dir):
    """Export level data with SGDK types."""
    levels = proj["levels"]
    count = len(levels)

    path_c = os.path.join(out_dir, "level_data.c")
    path_h = os.path.join(out_dir, "level_data.h")

    with open(path_h, "w") as fh:
        fh.write("/* level_data.h -- Generated by export_md.py */\n")
        fh.write("#ifndef LEVEL_DATA_H\n#define LEVEL_DATA_H\n\n")
        fh.write("#include <genesis.h>\n\n")
        fh.write(f"#define NUM_LEVELS {count}\n\n")
        fh.write("typedef struct {\n")
        fh.write("    u8 width, height;\n")
        fh.write("    const u8 *rle;\n")
        fh.write("    const u16 *row_offsets;\n")
        fh.write("    u8 entity_count;\n")
        fh.write("    const u8 *entities;\n")
        fh.write("} LevelInfo;\n\n")
        fh.write("extern const LevelInfo levels[NUM_LEVELS];\n\n")
        for i in range(count):
            fh.write(f"extern const u8 level_{i}_rle[];\n")
            fh.write(f"extern const u16 level_{i}_row_offsets[];\n")
            fh.write(f"extern const u8 level_{i}_entities[];\n")
        fh.write("\n#endif\n")

    with open(path_c, "w") as fc:
        fc.write("/* level_data.c -- Generated by export_md.py */\n")
        fc.write('#include "game.h"\n\n')

        for li, lvl in enumerate(levels):
            w = lvl["width"]
            h = lvl["height"]
            tiles = lvl["tiles"]
            entities = lvl.get("entities", [])

            rle = []
            row_offsets = []
            for y in range(h):
                row_offsets.append(len(rle))
                row = tiles[y]
                x = 0
                while x < w:
                    t = row[x]
                    run = 1
                    while x + run < w and row[x + run] == t and run < 255:
                        run += 1
                    rle.append(run)
                    rle.append(t)
                    x += run

            fc.write(f"const u8 level_{li}_rle[] = {{\n    ")
            for i, b in enumerate(rle):
                fc.write(f"0x{b:02X}")
                if i < len(rle) - 1: fc.write(",")
                if (i & 15) == 15: fc.write("\n    ")
            fc.write("\n};\n")

            fc.write(f"const u16 level_{li}_row_offsets[] = {{\n    ")
            for i, off in enumerate(row_offsets):
                fc.write(f"{off}")
                if i < len(row_offsets) - 1: fc.write(",")
                if (i & 15) == 15: fc.write("\n    ")
            fc.write("\n};\n")

            fc.write(f"const u8 level_{li}_entities[] = {{\n    ")
            if entities:
                for i, ent in enumerate(entities):
                    fc.write(f"{ent['x']},{ent['y']},{ent['type']},{ent.get('vx', 1)}")
                    if i < len(entities) - 1: fc.write(", ")
            else:
                fc.write("0")
            fc.write("\n};\n\n")

            print(f"  Level {li}: {w}x{h}, {len(rle)} bytes RLE, {len(entities)} entities")

        fc.write(f"const LevelInfo levels[NUM_LEVELS] = {{\n")
        for li, lvl in enumerate(levels):
            ent_count = len(lvl.get("entities", []))
            fc.write(f"    {{{lvl['width']}, {lvl['height']}, "
                     f"level_{li}_rle, level_{li}_row_offsets, "
                     f"{ent_count}, level_{li}_entities}}")
            if li < count - 1: fc.write(",")
            fc.write("\n")
        fc.write("};\n")

    print(f"  levels: {count} levels -> {path_c}")


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <game-rescue.json> <output_dir> [--max-levels N]")
        sys.exit(1)

    json_path = sys.argv[1]
    out_dir = sys.argv[2]
    max_levels = None

    if "--max-levels" in sys.argv:
        idx = sys.argv.index("--max-levels")
        max_levels = int(sys.argv[idx + 1])

    with open(json_path) as f:
        proj = json.load(f)

    if max_levels:
        proj["levels"] = proj["levels"][:max_levels]

    os.makedirs(out_dir, exist_ok=True)

    print(f"Exporting {json_path} -> {out_dir}/")
    export_tileset(proj, out_dir)
    export_levels(proj, out_dir)
    print("Done.")


if __name__ == "__main__":
    main()
