/* levels_export.h — Generated by GBC Workbench */
#ifndef LEVELS_EXPORT_H
#define LEVELS_EXPORT_H

#include <stdint.h>

#define LEVEL_0_W 20
#define LEVEL_0_H 21
extern const uint8_t level_0_rle[];

#define LEVEL_1_W 20
#define LEVEL_1_H 64
extern const uint8_t level_1_rle[];

#define LEVEL_2_W 20
#define LEVEL_2_H 96
extern const uint8_t level_2_rle[];

#define LEVEL_3_W 20
#define LEVEL_3_H 128
extern const uint8_t level_3_rle[];

#define LEVEL_4_W 40
#define LEVEL_4_H 112
extern const uint8_t level_4_rle[];

#define LEVEL_5_W 20
#define LEVEL_5_H 160
extern const uint8_t level_5_rle[];

#define LEVEL_6_W 40
#define LEVEL_6_H 176
extern const uint8_t level_6_rle[];

#define LEVEL_7_W 80
#define LEVEL_7_H 176
extern const uint8_t level_7_rle[];

#define LEVEL_8_W 120
#define LEVEL_8_H 176
extern const uint8_t level_8_rle[];

#define LEVEL_9_W 120
#define LEVEL_9_H 176
extern const uint8_t level_9_rle[];

#define LEVEL_10_W 120
#define LEVEL_10_H 176
extern const uint8_t level_10_rle[];

#define LEVEL_11_W 120
#define LEVEL_11_H 176
extern const uint8_t level_11_rle[];

#define LEVEL_12_W 120
#define LEVEL_12_H 176
extern const uint8_t level_12_rle[];

#define LEVEL_13_W 120
#define LEVEL_13_H 176
extern const uint8_t level_13_rle[];

#define LEVEL_14_W 120
#define LEVEL_14_H 176
extern const uint8_t level_14_rle[];

#define LEVEL_15_W 120
#define LEVEL_15_H 176
extern const uint8_t level_15_rle[];

#define LEVEL_16_W 120
#define LEVEL_16_H 176
extern const uint8_t level_16_rle[];

#define LEVEL_17_W 120
#define LEVEL_17_H 176
extern const uint8_t level_17_rle[];

#define LEVEL_18_W 120
#define LEVEL_18_H 176
extern const uint8_t level_18_rle[];

#define LEVEL_19_W 120
#define LEVEL_19_H 176
extern const uint8_t level_19_rle[];


#endif
