/* palettes_export.h — Generated by GBC Workbench */
#ifndef PALETTES_EXPORT_H
#define PALETTES_EXPORT_H

#include <stdint.h>

#define EXPORT_BG_PAL_COUNT 8
#define EXPORT_SPR_PAL_COUNT 5

extern const uint16_t exported_bg_palettes[32];
extern const uint16_t exported_spr_palettes[20];

#endif
