/* screens_export.c — Generated by GBC Workbench */
#include "screens_export.h"
#include "tileset_export.h"
#include <gb/gb.h>

#pragma bank 5

BANKREF(exported_screens)

/* Placeholder: will be regenerated when you export from Workbench */
const ExportedScreen exported_screens[1] = {
    { /* title */
        {{0}},
        {{0}}
    }
};
