/* screens_export.h — Generated by GBC Workbench */
#ifndef SCREENS_EXPORT_H
#define SCREENS_EXPORT_H

#include <stdint.h>

#define SCREEN_TILES_W 20
#define SCREEN_TILES_H 18
#define NUM_SCREENS 1

typedef struct {
    uint8_t tiles[18][20];
    uint8_t attrs[18][20];
} ExportedScreen;

extern const ExportedScreen exported_screens[1];

#define SCREEN_0 0  /* title */

#endif
