/* sprites_export.h — Generated by GBC Workbench */
#ifndef SPRITES_EXPORT_H
#define SPRITES_EXPORT_H

#include <stdint.h>

#define EXPORT_SPRITE_COUNT 17

extern const uint8_t spr_bat_0[32];
extern const uint8_t spr_bat_1[32];
extern const uint8_t spr_cave_h_0[32];
extern const uint8_t spr_cave_v_0[32];
extern const uint8_t spr_dynamite_0[32];
extern const uint8_t spr_explode_0[32];
extern const uint8_t spr_hud_live[32];
extern const uint8_t spr_lava_0[32];
extern const uint8_t spr_miner_0[32];
extern const uint8_t spr_player_fly_0[32];
extern const uint8_t spr_player_fly_1[32];
extern const uint8_t spr_player_fly_2[32];
extern const uint8_t spr_player_walk_0[32];
extern const uint8_t spr_player_walk_1[32];
extern const uint8_t spr_snake_0[32];
extern const uint8_t spr_spider_0[32];
extern const uint8_t spr_wall_0[32];

#endif
