/* tileset_export.h — Generated by GBC Workbench */
#ifndef TILESET_EXPORT_H
#define TILESET_EXPORT_H

#include <stdint.h>

#define TILESET_COUNT 141
extern const uint8_t tileset_data[141][16];

extern const uint8_t tile_palettes[141];

#endif

