/* tileset_export.h — Generated by GBC Workbench */
#ifndef TILESET_EXPORT_H
#define TILESET_EXPORT_H

#include <stdint.h>

#define TILESET_COUNT 189
extern const uint8_t tileset_data[189][16];

#endif
