/* tileset_export.h — Generated by GBC Workbench */
#ifndef TILESET_EXPORT_H
#define TILESET_EXPORT_H

#include <stdint.h>

#define TILESET_COUNT 160
extern const uint8_t tileset_data[160][16];
extern const uint8_t tile_palettes[160];

#endif
