// Generated by level_editor.py
// Vectrex R.E.S.C.U.E. level data

#ifndef LEVELS_H
#define LEVELS_H
#include "hero.h"

// ============================================================
// START (2 room(s))
// ============================================================

#define L1R1_WALL_COUNT 1
static const int8_t l1r1_walls[] = {
    -3, -30, 17, 15,   // wall 0 (destroyable)
};

#define L1R1_ENEMY_COUNT 0
static const int8_t l1r1_enemies[] = { 0, 0, 0 };

#define L1R1_START_X  -60
#define L1R1_START_Y  40
#define L1R1_MINER_X  0
#define L1R1_MINER_Y  -42

// Cave outline polylines for R1:
//   path 0: (-85,45) -> (-85,15) -> (-100,15) -> (-100,-20) -> (-15,-20) -> (-15,-50) -> (-125,-50) -> (-125,45) -> (-85,45)
//   path 1: (-35,45) -> (-35,15) -> (100,15) -> (100,-20) -> (15,-20) -> (15,-50)
//   path 2: (-35,45) -> (125,45) -> (125,-50) -> (15,-50)
//   path 3: (-125,15) -> (-100,15)
//   path 4: (-125,-20) -> (-100,-20)
//   path 5: (100,15) -> (125,15)
//   path 6: (100,-20) -> (125,-20)

#define L1R2_WALL_COUNT 0
static const int8_t l1r2_walls[] = { 0, 0, 0, 0 };

#define L1R2_ENEMY_COUNT 1
static const int8_t l1r2_enemies[] = {
    -45, 10, 1,   // enemy 0
};

#define L1R2_START_X  -113
#define L1R2_START_Y  48
#define L1R2_MINER_X  -80
#define L1R2_MINER_Y  -5

// Cave outline polylines for R2:
//   path 0: (-15,50) -> (-125,50) -> (-125,-50) -> (125,-50) -> (125,50) -> (15,50)
//   path 1: (-15,50) -> (-15,20) -> (-125,20)
//   path 2: (-85,20) -> (-85,-15)
//   path 3: (-125,-15) -> (125,-15)
//   path 4: (85,-15) -> (85,20) -> (125,20)
//   path 5: (85,20) -> (15,20) -> (15,50)

// Room lookup tables for START
static const int8_t * const l1_room_walls[] = {
    l1r1_walls,
    l1r2_walls,
};
static const uint8_t l1_room_wall_counts[] = {
    L1R1_WALL_COUNT,
    L1R2_WALL_COUNT,
};
static const int8_t * const l1_room_enemies[] = {
    l1r1_enemies,
    l1r2_enemies,
};
static const uint8_t l1_room_enemy_counts[] = {
    L1R1_ENEMY_COUNT,
    L1R2_ENEMY_COUNT,
};
static const int8_t l1_room_starts[] = {
    L1R1_START_X, L1R1_START_Y,
    L1R2_START_X, L1R2_START_Y,
};
static const int8_t l1_room_miners[] = {
    L1R1_MINER_X, L1R1_MINER_Y,
    L1R2_MINER_X, L1R2_MINER_Y,
};
static const uint8_t l1_room_exits[] = {
    NONE, NONE, NONE, 1,   // room 0
    NONE, NONE, 0, NONE,   // room 1
};
static const int8_t l1_room_bounds[] = {
    -128, 127, 50, -50,   // room 0
    -128, 127, 50, -50,   // room 1
};
static const char l1_name[] = "START";
#define L1_NAME_X -22

#endif
