// Generated by level_editor.py
// Vectrex R.E.S.C.U.E. VLC sprite data

#include <vectrex.h>

int8_t player_right[] = {
    5, 11,  // hw, hh (scaled: raw 6,13 x 0x6A/0x7F)
    10, 6,  // oy, ox (center to VLC start)
    13,  // 14 vectors (VLC count-1)
       0,   -6,
      -4,    0,
      -2,    2,
       0,   -8,
      -5,    0,
      -4,    6,
      -4,   -1,
      -4,   -1,
       0,    2,
       3,    2,
       5,    1,
       9,    1,
       0,    2,
       6,    0,
};

int8_t player_left[] = {
    5, 11,  // hw, hh (scaled: raw 6,13 x 0x6A/0x7F)
    10, -6,  // oy, ox (center to VLC start)
    13,  // 14 vectors (VLC count-1)
       0,    6,
      -4,    0,
      -2,   -2,
       0,    8,
      -5,    0,
      -4,   -6,
      -4,    1,
      -4,    1,
       0,   -2,
       3,   -2,
       5,   -1,
       9,   -1,
       0,   -2,
       6,    0,
};

int8_t player_walk_right_f0[] = {
    5, 12,  // hw, hh (scaled: raw 6,14 x 0x6A/0x7F)
    10, 6,  // oy, ox (center to VLC start)
    16,  // 17 vectors (VLC count-1)
       0,   -6,
      -4,    0,
      -2,    2,
       0,   -8,
      -5,    0,
      -4,    6,
      -4,   -1,
      -5,   -3,
       0,    1,
       5,    4,
      -5,    3,
       0,    1,
       5,   -2,
       4,    0,
       9,    1,
       0,    2,
       6,    0,
};

int8_t player_walk_right_f1[] = {
    5, 12,  // hw, hh (scaled: raw 6,14 x 0x6A/0x7F)
    10, 6,  // oy, ox (center to VLC start)
    16,  // 17 vectors (VLC count-1)
       0,   -6,
      -4,    0,
      -2,    2,
       0,   -8,
      -5,    0,
      -4,    6,
      -4,   -1,
      -5,    0,
       0,    1,
       5,    1,
      -5,    1,
       0,    1,
       5,    0,
       4,    0,
       9,    1,
       0,    2,
       6,    0,
};

int8_t player_walk_left_f0[] = {
    5, 12,  // hw, hh (scaled: raw 6,14 x 0x6A/0x7F)
    10, -6,  // oy, ox (center to VLC start)
    16,  // 17 vectors (VLC count-1)
       0,    6,
      -4,    0,
      -2,   -2,
       0,    8,
      -5,    0,
      -4,   -6,
      -4,    1,
      -5,    3,
       0,   -1,
       4,   -4,
      -4,   -3,
       0,   -1,
       5,    2,
       4,    0,
       9,   -1,
       0,   -2,
       6,    0,
};

int8_t player_walk_left_f1[] = {
    5, 12,  // hw, hh (scaled: raw 6,14 x 0x6A/0x7F)
    10, -6,  // oy, ox (center to VLC start)
    16,  // 17 vectors (VLC count-1)
       0,    6,
      -4,    0,
      -2,   -2,
       0,    8,
      -5,    0,
      -4,   -6,
      -4,    1,
      -5,    0,
       0,   -1,
       5,   -1,
      -5,   -1,
       0,   -1,
       5,    0,
       4,    0,
       9,   -1,
       0,   -2,
       6,    0,
};

int8_t snake_right_f0[] = {
    7, 2,  // hw, hh (scaled: raw 9,3 x 0x60/0x7F)
    2, -7,  // oy, ox (center to VLC start)
    9,  // 10 vectors (VLC count-1)
      -2,    7,
       3,    4,
      -2,    3,
       2,    2,
      -4,    0,
       0,   -2,
       2,   -3,
      -3,   -4,
       2,   -7,
       2,    0,
};

int8_t snake_right_f1[] = {
    7, 2,  // hw, hh (scaled: raw 9,3 x 0x60/0x7F)
    1, -8,  // oy, ox (center to VLC start)
    11,  // 12 vectors (VLC count-1)
      -2,    4,
       3,    4,
      -2,    4,
       1,    3,
       2,    2,
      -4,    0,
       0,   -2,
      -1,   -3,
       2,   -4,
      -2,   -4,
       1,   -4,
       2,    0,
};

int8_t snake_left_f0[] = {
    7, 2,  // hw, hh (scaled: raw 9,3 x 0x60/0x7F)
    0, 8,  // oy, ox (center to VLC start)
    11,  // 12 vectors (VLC count-1)
       3,   -4,
      -3,   -4,
       3,   -4,
      -2,   -3,
       2,   -2,
      -4,    0,
       0,    2,
       2,    3,
      -3,    4,
       3,    4,
      -3,    4,
       2,    0,
};

int8_t snake_left_f1[] = {
    7, 2,  // hw, hh (scaled: raw 9,3 x 0x60/0x7F)
    1, 8,  // oy, ox (center to VLC start)
    11,  // 12 vectors (VLC count-1)
      -2,   -4,
       3,   -4,
      -2,   -4,
       1,   -3,
       2,   -2,
      -4,    0,
       0,    2,
      -1,    3,
       2,    4,
      -2,    4,
       1,    4,
       2,    0,
};

int8_t bat_f0[] = {
    6, 5,  // hw, hh (scaled: raw 8,7 x 0x60/0x7F)
    0, -5,  // oy, ox (center to VLC start)
    7,  // 8 vectors (VLC count-1)
       2,    4,
       0,    2,
       5,    3,
      -5,    0,
      -1,    4,
      -2,    0,
       0,  -10,
       1,   -3,
};

int8_t bat_f1[] = {
    6, 5,  // hw, hh (scaled: raw 8,7 x 0x60/0x7F)
    0, -5,  // oy, ox (center to VLC start)
    7,  // 8 vectors (VLC count-1)
       2,    4,
       0,    2,
      -7,    3,
       7,    0,
      -1,    4,
      -2,    0,
       0,  -10,
       1,   -3,
};

int8_t miner[] = {
    6, 6,  // hw, hh (scaled: raw 8,8 x 0x60/0x7F)
    3, 0,  // oy, ox (center to VLC start)
    17,  // 18 vectors (VLC count-1)
       0,   -4,
      -4,    0,
       0,   -2,
      -5,    0,
      -2,    2,
       0,    3,
       1,    1,
       1,    4,
      -2,    1,
       0,    3,
       1,    0,
       1,   -2,
       2,   -3,
      -1,   -3,
       4,    0,
       1,   -1,
       1,    1,
       2,    0,
};

int8_t dynamite[] = {
    1, 2,  // hw, hh (scaled: raw 2,5 x 0x30/0x7F)
    5, -2,  // oy, ox (center to VLC start)
    3,  // 4 vectors (VLC count-1)
       0,    4,
     -10,    0,
       0,   -4,
      10,    0,
};

int8_t spider[] = {
    5, 4,  // hw, hh (scaled: raw 6,5 x 0x60/0x7F)
    3, -5,  // oy, ox (center to VLC start)
    7,  // 8 vectors (VLC count-1)
       2,    2,
       0,    2,
      -2,    0,
       0,    3,
       2,    0,
       0,   -3,
       0,    6,
      -2,    1,
};

