/* level_data.h -- Generated by export tool */
#ifndef LEVEL_DATA_H
#define LEVEL_DATA_H

#include <genesis.h>

#define NUM_LEVELS 1

typedef struct {
    u8 width, height;
    const u8 *rle;
    const u16 *row_offsets;
    u8 entity_count;
    const u8 *entities;
} LevelInfo;

extern const LevelInfo levels[NUM_LEVELS];

extern const u8 level_0_rle[];
extern const u16 level_0_row_offsets[];
extern const u8 level_0_entities[];

#endif
