// Generated by level_editor.py
// Cave Diver level data (placeholder)

#ifndef LEVELS_H
#define LEVELS_H

#include "cave.h"

// TODO: generate level data via level_editor.py --game cave --export

#endif
