/* level_data.h — Generated by export_c64.py */
#ifndef LEVEL_DATA_H
#define LEVEL_DATA_H

#include <stdint.h>

#define NUM_LEVELS 5

typedef struct {
    uint8_t width, height;
    const uint8_t *rle;
    const uint16_t *row_offsets;
    uint8_t entity_count;
    const uint8_t *entities;
} LevelInfo;

extern const LevelInfo levels[NUM_LEVELS];

extern const uint8_t level_0_rle[];
extern const uint16_t level_0_row_offsets[];
extern const uint8_t level_0_entities[];
extern const uint8_t level_1_rle[];
extern const uint16_t level_1_row_offsets[];
extern const uint8_t level_1_entities[];
extern const uint8_t level_2_rle[];
extern const uint16_t level_2_row_offsets[];
extern const uint8_t level_2_entities[];
extern const uint8_t level_3_rle[];
extern const uint16_t level_3_row_offsets[];
extern const uint8_t level_3_entities[];
extern const uint8_t level_4_rle[];
extern const uint16_t level_4_row_offsets[];
extern const uint8_t level_4_entities[];

#endif
