/* level_data.h — Generated by export_c64.py */
#ifndef LEVEL_DATA_H
#define LEVEL_DATA_H

#include <stdint.h>

#define NUM_LEVELS 20

typedef struct {
    uint8_t width, height;
    const uint8_t *rle;
    const uint16_t *row_offsets;
    uint8_t entity_count;
    const uint8_t *entities;
} LevelInfo;

extern const LevelInfo levels[NUM_LEVELS];

extern const uint8_t level_0_rle[];
extern const uint16_t level_0_row_offsets[];
extern const uint8_t level_0_entities[];
extern const uint8_t level_1_rle[];
extern const uint16_t level_1_row_offsets[];
extern const uint8_t level_1_entities[];
extern const uint8_t level_2_rle[];
extern const uint16_t level_2_row_offsets[];
extern const uint8_t level_2_entities[];
extern const uint8_t level_3_rle[];
extern const uint16_t level_3_row_offsets[];
extern const uint8_t level_3_entities[];
extern const uint8_t level_4_rle[];
extern const uint16_t level_4_row_offsets[];
extern const uint8_t level_4_entities[];
extern const uint8_t level_5_rle[];
extern const uint16_t level_5_row_offsets[];
extern const uint8_t level_5_entities[];
extern const uint8_t level_6_rle[];
extern const uint16_t level_6_row_offsets[];
extern const uint8_t level_6_entities[];
extern const uint8_t level_7_rle[];
extern const uint16_t level_7_row_offsets[];
extern const uint8_t level_7_entities[];
extern const uint8_t level_8_rle[];
extern const uint16_t level_8_row_offsets[];
extern const uint8_t level_8_entities[];
extern const uint8_t level_9_rle[];
extern const uint16_t level_9_row_offsets[];
extern const uint8_t level_9_entities[];
extern const uint8_t level_10_rle[];
extern const uint16_t level_10_row_offsets[];
extern const uint8_t level_10_entities[];
extern const uint8_t level_11_rle[];
extern const uint16_t level_11_row_offsets[];
extern const uint8_t level_11_entities[];
extern const uint8_t level_12_rle[];
extern const uint16_t level_12_row_offsets[];
extern const uint8_t level_12_entities[];
extern const uint8_t level_13_rle[];
extern const uint16_t level_13_row_offsets[];
extern const uint8_t level_13_entities[];
extern const uint8_t level_14_rle[];
extern const uint16_t level_14_row_offsets[];
extern const uint8_t level_14_entities[];
extern const uint8_t level_15_rle[];
extern const uint16_t level_15_row_offsets[];
extern const uint8_t level_15_entities[];
extern const uint8_t level_16_rle[];
extern const uint16_t level_16_row_offsets[];
extern const uint8_t level_16_entities[];
extern const uint8_t level_17_rle[];
extern const uint16_t level_17_row_offsets[];
extern const uint8_t level_17_entities[];
extern const uint8_t level_18_rle[];
extern const uint16_t level_18_row_offsets[];
extern const uint8_t level_18_entities[];
extern const uint8_t level_19_rle[];
extern const uint16_t level_19_row_offsets[];
extern const uint8_t level_19_entities[];

#endif
