// Generated by level_editor.py
// Vectrex H.E.R.O. level data

#ifndef LEVELS_H
#define LEVELS_H
#include "hero.h"

// Layout 0
static const int8_t layout_0_cave[] = {
    8, 50, -85, -30, 0, 0, -15, -35, 0, 0, 85, -35,
    0, 0, -110, 100, 0, 0, 40, 10, 50, -35, -30, 0,
    0, 127, 0, 8, -35, 0, 0, -85, -35, 0, 0, 110,
    100, 0, 0, -33, 0, -127, 1, 20, -125, 0, 25, 1,
    20, 100, 0, 25, 0,
};
#define LAYOUT_0_SEG_COUNT 18
static const int8_t layout_0_cave_segs[] = {
    -85, 50, -85, 20,
    -85, 20, -100, 20,
    -100, 20, -100, -15,
    -100, -15, -15, -15,
    -15, -15, -15, -50,
    -15, -50, -125, -50,
    -125, -50, -125, 50,
    -125, 50, -85, 50,
    -35, 50, -35, 20,
    -35, 20, 100, 20,
    100, 20, 100, -15,
    100, -15, 15, -15,
    15, -15, 15, -50,
    -35, 50, 125, 50,
    125, 50, 125, -50,
    125, -50, 15, -50,
    -125, 20, -100, 20,
    100, 20, 125, 20,
};

// Layout 1
static const int8_t layout_1_cave[] = {
    10, 20, -125, 0, 110, 30, 0, 0, -110, -100, 0, 0,
    127, 0, 123, 100, 0, 0, -110, -30, 0, 0, 70, 5,
    20, -85, -35, 0, 0, 127, 0, 43, 35, 0, 0, 40,
    0,
};
#define LAYOUT_1_SEG_COUNT 13
static const int8_t layout_1_cave_segs[] = {
    -15, 50, -125, 50,
    -125, 50, -125, -50,
    -125, -50, 125, -50,
    125, -50, 125, 50,
    125, 50, 15, 50,
    -15, 50, -15, 20,
    -15, 20, -125, 20,
    -85, 20, -85, -15,
    85, -15, 85, 20,
    85, 20, 125, 20,
    85, 20, 15, 20,
    15, 20, 15, 50,
    -85, -15, 85, -15,
};

// ============================================================
// Level 1 (2 room(s))
// ============================================================

#define L1R1_WALL_COUNT 1
static const int8_t l1r1_walls[] = {
    2, -30, 15, 10,   // wall 0 (destroyable)
};

#define L1R1_ENEMY_COUNT 0
static const int8_t l1r1_enemies[] = { 0, 0, 0, 0 };

#define L1R1_START_X  -70
#define L1R1_START_Y  40
#define L1R1_MINER_X  0
#define L1R1_MINER_Y  -40

#define L1R2_WALL_COUNT 0
static const int8_t l1r2_walls[] = { 0, 0, 0, 0 };

#define L1R2_ENEMY_COUNT 1
static const int8_t l1r2_enemies[] = {
    -40, 15, 1, 1,   // enemy 0 (spider)
};

#define L1R2_START_X  -75
#define L1R2_START_Y  40
#define L1R2_MINER_X  -80
#define L1R2_MINER_Y  -10

// Room lookup tables for level 1
static const int8_t * const l1_room_caves[] = {
    layout_0_cave,    // room 0 uses layout 0
    layout_1_cave,    // room 1 uses layout 1
};
static const int8_t * const l1_room_walls[] = {
    l1r1_walls,
    l1r2_walls,
};
static const uint8_t l1_room_wall_counts[] = {
    L1R1_WALL_COUNT,
    L1R2_WALL_COUNT,
};
static const int8_t * const l1_room_enemies[] = {
    l1r1_enemies,
    l1r2_enemies,
};
static const uint8_t l1_room_enemy_counts[] = {
    L1R1_ENEMY_COUNT,
    L1R2_ENEMY_COUNT,
};
static const int8_t l1_room_starts[] = {
    L1R1_START_X, L1R1_START_Y,
    L1R2_START_X, L1R2_START_Y,
};
static const int8_t l1_room_miners[] = {
    L1R1_MINER_X, L1R1_MINER_Y,
    L1R2_MINER_X, L1R2_MINER_Y,
};
static const int8_t * const l1_room_cave_segs[] = {
    layout_0_cave_segs,
    layout_1_cave_segs,
};
static const uint8_t l1_room_seg_counts[] = {
    LAYOUT_0_SEG_COUNT,
    LAYOUT_1_SEG_COUNT,
};
static const uint8_t l1_room_has_miner[] = {
    0,
    1,
};
static const uint8_t l1_room_has_lava[] = {
    0,
    1,
};
static const uint8_t l1_room_exits[] = {
    NONE, NONE, NONE, 1,   // room 0
    NONE, NONE, 0, NONE,   // room 1
};
static const int8_t l1_room_bounds[] = {
    -128, 127, 50, -50,   // room 0
    -128, 127, 50, -50,   // room 1
};
#endif
