// Generated by level_editor.py
// Vectrex H.E.R.O. VLC sprite data

#include <vectrex.h>

int8_t player[] = {
    8, 11,  // hw, hh (scaled: raw 9,13 × 0x6A/0x7F)
    35,  // 36 vectors (VLC count-1)
       0,   -4,
      -1,   -2,
      -2,    0,
       0,    2,
      -1,    0,
      -1,   -2,
       0,   -2,
       8,   -1,
       0,    4,
       1,    0,
       0,  -10,
      -1,    0,
       0,    5,
      -7,    0,
      -1,   -2,
      -3,    0,
      -1,    1,
      -1,    1,
      -1,    2,
      -1,    2,
      -4,    0,
      -1,   -2,
      -5,    0,
       0,    1,
       3,    1,
       1,    2,
       3,    0,
       1,    2,
       3,    0,
       2,    0,
       0,    2,
       3,    0,
       0,   -2,
       1,    0,
       1,    2,
       4,    0,
};

int8_t bat_f0[] = {
    6, 5,  // hw, hh (scaled: raw 8,7 × 0x60/0x7F)
    7,  // 8 vectors (VLC count-1)
       2,    4,
       0,    2,
       5,    3,
      -5,    0,
      -1,    4,
      -2,    0,
       0,  -10,
       1,   -3,
};

int8_t bat_f1[] = {
    6, 5,  // hw, hh (scaled: raw 8,7 × 0x60/0x7F)
    7,  // 8 vectors (VLC count-1)
       2,    4,
       0,    2,
      -7,    3,
       7,    0,
      -1,    4,
      -2,    0,
       0,  -10,
       1,   -3,
};

int8_t miner[] = {
    6, 6,  // hw, hh (scaled: raw 8,8 × 0x60/0x7F)
    24,  // 25 vectors (VLC count-1)
       0,   -4,
      -4,    0,
       0,   -2,
      -5,    0,
       0,    2,
      -2,    0,
       0,    3,
       1,    1,
       0,    2,
       1,    1,
       0,    2,
      -2,    0,
       0,    3,
       1,    0,
       0,   -2,
       2,    0,
       0,   -2,
       1,   -1,
      -1,   -1,
       0,   -2,
       4,    0,
       0,   -1,
       1,    0,
       1,    1,
       2,    0,
};

int8_t dynamite[] = {
    1, 2,  // hw, hh (scaled: raw 2,5 × 0x30/0x7F)
    3,  // 4 vectors (VLC count-1)
       0,    4,
     -10,    0,
       0,   -4,
      10,    0,
};

