// Generated by level_editor.py
// Vectrex H.E.R.O. VLC sprite data

#ifndef SPRITES_H
#define SPRITES_H

extern int8_t player[];
extern int8_t bat_f0[];
extern int8_t bat_f1[];
extern int8_t miner[];
extern int8_t dynamite[];

#endif

